export {
  useAnnouncements,
  useCreateAnnouncement,
  useCreateSubmission,
  useDebounce,
  useEvent,
  useEvents,
  useFeaturedEvent,
  useJudgeAssignmentMap,
  useJudgeAssignments,
  useJudgeScores,
  useLeaderboard,
  useOrganizerJudges,
  useOrganizerRegistrations,
  useOrganizerStats,
  useOrganizerSubmissions,
  useRegistrationCheck,
  useSaveJudgeAssignments,
  useSubmission,
  useSubmitScore,
  useTeam,
  useTeamLookup,
  useUpdateSubmission,
  useValidateInviteCode,
} from '@/lib/api/hooks'
